import { createStore } from 'vuex'
import createPersistedState from 'vuex-persistedstate'
import { auth } from './auth'

export default createStore({
  state: {
    products: [
        {id: 1, kdbrg: 'AX00001', name: 'Fesh Salmon', tipe: 'RM', satuan: 'Kg', sbeli: "Kg", konversi: "1", stock: 10, kdjenis: 1, no: 1, active: true, image: 'fresh-salmon.png', qtymin: 0, qtyday: 0},
        {id: 2, kdbrg: 'AX00002', name: 'Telur Ayam', tipe: 'RM', satuan: 'Kg', sbeli: "Peti", konversi: "20", stock: 13, kdjenis: 1, no: 2, active: true, image: 'telur-ayam.png', qtymin: 0, qtyday: 0},
        {id: 3, kdbrg: 'AX00003', name: 'Bawang Merah', tipe: 'RM', satuan: 'Kg', sbeli: "Karung", konversi: "30", stock: 11, kdjenis: 1, no: 3, active: true, image: 'bawang-merah.png', qtymin: 0, qtyday: 0},
        {id: 4, kdbrg: 'AX00004', name: 'Bawang Putih', tipe: 'RM', satuan: 'Kg', sbeli: "Karung", konversi: "30", stock: 11, kdjenis: 1, no: 4, active: true, image: 'bawang-putih.png', qtymin: 0, qtyday: 0},
        {id: 5, kdbrg: 'AX00005', name: 'Garam', tipe: 'RM', satuan: 'Kg', sbeli: "Kg", konversi: "1", stock: 21, kdjenis: 2, no: 5, active: true, image: 'garam.png', qtymin: 15, qtyday: 3},
        {id: 6, kdbrg: 'AX00006', name: 'Gula', tipe: 'RM', satuan: 'Kg', sbeli: "Kg", konversi: "1", stock: 22, kdjenis: 2, no: 6, active: true, image: 'gula.png', qtymin: 15, qtyday: 3},
        {id: 7, kdbrg: 'AX00007', name: 'Beras Raja', tipe: 'RM', satuan: 'Kg', sbeli: "Karung", konversi: "50", stock: 50, kdjenis: 2, no: 7, active: true, image: 'beras-raja.png', qtymin: 30, qtyday: 5},
        {id: 8, kdbrg: 'AX00008', name: 'Cabe Rawit', tipe: 'RM', satuan: 'Kg', sbeli: "Kg", konversi: "1", stock: 13, kdjenis: 1, no: 8, active: true, image: 'cabe-rawit.png', qtymin: 0, qtyday: 0},
        {id: 9, kdbrg: 'AX00009', name: 'Merica Putih', tipe: 'RM', satuan: 'Kg', sbeli: "Kg", konversi: "1", stock: 8, kdjenis: 1, no: 9, active: true, image: 'merica-putih.png', qtymin: 0, qtyday: 0},
        {id: 10, kdbrg: 'AX00010', name: 'Gula Aren', tipe: 'RM', satuan: 'Kg', sbeli: "Kg", konversi: "1", stock: 5, kdjenis: 1, no: 10, active: true, image: 'gula-aren.png', qtymin: 0, qtyday: 0},
        {id: 11, kdbrg: 'AX00011', name: 'Kecap Bango', tipe: 'RM', satuan: 'Botol', sbeli: "Box", konversi: "15", stock: 6, kdjenis: 2, no: 11, active: true, image: 'kecap-bango.png', qtymin: 10, qtyday: 2},
        {id: 12, kdbrg: 'AX00012', name: 'Kecap ABC', tipe: 'RM', satuan: 'Botol', sbeli: "Box", konversi: "15", stock: 8, kdjenis: 2, no: 12, active: true, image: 'kecap-abc.png', qtymin: 10, qtyday: 2},
        {id: 13, kdbrg: 'AX00013', name: 'Sauce Tomat Belibis', tipe: 'RM', satuan: 'Botol', sbeli: "Box", konversi: "15", stock: 7, kdjenis: 2, no: 13, active: true, image: 'tomat-belibis.png', qtymin: 10, qtyday: 2},
        {id: 14, kdbrg: 'AX00014', name: 'Saori Saus Tiram', tipe: 'RM', satuan: 'Botol', sbeli: "Box", konversi: "15", stock: 10, kdjenis: 2, no: 14, active: true, image: 'saori-saus-tiram.png', qtymin: 10, qtyday: 1},
        {id: 15, kdbrg: 'AX00015', name: 'Kaldu Jamur', tipe: 'RM', satuan: 'Jar', sbeli: "Box", stock: 5, konversi: "15", kdjenis: 2, no: 15, active: true, image: 'kaldu-jamur.png', qtymin: 5, qtyday: 1},
        {id: 16, kdbrg: 'AX00016', name: 'Kecap Inggris ABC', tipe: 'RM', satuan: 'Botol', sbeli: "Box", konversi: "15", stock: 9, kdjenis: 2, no: 16, active: true, image: 'kecap-inggris-abc.png', qtymin: 10, qtyday: 1},
        {id: 17, kdbrg: 'AX00017', name: 'Saus BBQ', tipe: 'WIP', satuan: 'Kg', sbeli: "Box", konversi: "15", stock: 4, kdjenis: 2, no: 17, active: true, image: 'saus-bbq.png', qtymin: 15, qtyday: 3},
        {id: 18, kdbrg: 'AX00018', name: 'Mayonnaise Mayumi', tipe: 'RM', satuan: 'Kg', sbeli: "Box", konversi: "15", stock: 12, kdjenis: 2, no: 18, active: true, image: 'mayumi.png', qtymin: 10, qtyday: 2},
        {id: 19, kdbrg: 'AX00019', name: 'Black Pepper', tipe: 'RM', satuan: 'Kg', sbeli: "Kg", konversi: "1", stock: 4, kdjenis: 1, no: 19, active: true, image: 'black-pepper.png', qtymin: 0, qtyday: 0},
        {id: 20, kdbrg: 'AX00020', name: 'Cabe Merah', tipe: 'RM', satuan: 'Kg', sbeli: "Kg", konversi: "1", stock: 10, kdjenis: 1, no: 20, active: true, image: 'cabe-merah.png', qtymin: 0, qtyday: 0},
        {id: 21, kdbrg: 'AX00021', name: 'Wasabi', tipe: 'RM', satuan: 'Kg', sbeli: "Kg", konversi: "1", stock: 8, kdjenis: 1, no: 21, active: true, image: 'wasabi.png', qtymin: 0, qtyday: 0},
        {id: 22, kdbrg: 'AX00022', name: 'Jeruk Nipis', tipe: 'RM', satuan: 'Kg', sbeli: "Kg", konversi: "1", stock: 7, kdjenis: 1, no: 22, active: true, image: 'jeruk-nipis.png', qtymin: 0, qtyday: 0},
        {id: 23, kdbrg: 'AX00023', name: 'Tomat', tipe: 'RM', satuan: 'Kg', sbeli: "Kg", konversi: "1", stock: 9, kdjenis: 1, no: 23, active: true, image: 'tomat.png', qtymin: 0, qtyday: 0},
        {id: 24, kdbrg: 'AX00024', name: 'Minyak Wijen', tipe: 'RM', satuan: 'Botol', sbeli: "Box", konversi: "15", stock: 13, kdjenis: 2, no: 23, active: true, image: 'minyak-wijen.png', qtymin: 8, qtyday: 2},
        {id: 25, kdbrg: 'AX00025', name: 'Chili Oil', tipe: 'RM', satuan: 'Botol', sbeli: "Box", konversi: "15", stock: 11, kdjenis: 2, no: 20, active: true, image: 'chili-oil.png', qtymin: 8, qtyday: 2},
        {id: 26, kdbrg: 'AX00026', name: 'Kecap Ikan', tipe: 'RM', satuan: 'Botol', sbeli: "Box", konversi: "15", stock: 8, kdjenis: 2, no: 20, active: true, image: 'kecap-ikan.png', qtymin: 10, qtyday: 2},
        {id: 27, kdbrg: 'AX00027', name: 'Kecap Asin', tipe: 'RM', satuan: 'Botol', sbeli: "Box", konversi: "15", stock: 14, kdjenis: 2, no: 20, active: true, image: 'kecap-asin.png', qtymin: 10, qtyday: 2},
    ],
    food: [
        {no: 0, id: 'FG0001', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0002', name: 'Australian Tender Minutes Steak', category: 'Western', price: 248000, stock: 8, active: true, image: 'aust-tender.png'},
        {no: 0, id: 'FG0003', name: 'Caesar Salad', category: 'Soup & Salad', price: 45000, stock: 16, active: true, image: 'caesar.png'},
        {no: 0, id: 'FG0004', name: 'Creamy Mushroom Soup', category: 'Soup & Salad', price: 55000, stock: 11, active: true, image: 'creamy-mushroom.png'},
        {no: 0, id: 'FG0005', name: 'Chicken Steak', category: 'Western', price: 108000, stock: 17, active: true, image: 'chicken-steak.png'},
        {no: 0, id: 'FG0006', name: 'Tom Yum', category: 'Asia', price: 70000, stock: 18, active: true, image: 'tomyum.png'},
        {no: 0, id: 'FG0007', name: 'Jajangmyeon', category: 'Asia', price: 80000, stock: 14, active: true, image: 'jajangmyeon.png'},
        {no: 0, id: 'FG0008', name: 'Bulgogi', category: 'Asia', price: 88000, stock: 19, active: true, image: 'bulgogi.png'},
        {no: 0, id: 'FG0009', name: 'Kimchi', category: 'Asia', price: 50000, stock: 8, active: false, image: 'kimchi.png'},
        {no: 0, id: 'FG0010', name: 'Fish and Chips', category: 'Western', price: 90000, stock: 24, active: true, image: 'fish-chips.png'},
        {no: 0, id: 'FG0011', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0012', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0013', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0014', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0015', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0016', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0017', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0018', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0019', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0020', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0021', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0022', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0023', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0024', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0025', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0026', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0027', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0001', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0002', name: 'Australian Tender Minutes Steak', category: 'Western', price: 248000, stock: 8, active: true, image: 'aust-tender.png'},
        {no: 0, id: 'FG0003', name: 'Caesar Salad', category: 'Soup & Salad', price: 45000, stock: 16, active: true, image: 'caesar.png'},
        {no: 0, id: 'FG0004', name: 'Creamy Mushroom Soup', category: 'Soup & Salad', price: 55000, stock: 11, active: true, image: 'creamy-mushroom.png'},
        {no: 0, id: 'FG0005', name: 'Chicken Steak', category: 'Western', price: 108000, stock: 17, active: true, image: 'chicken-steak.png'},
        {no: 0, id: 'FG0006', name: 'Tom Yum', category: 'Asia', price: 70000, stock: 18, active: true, image: 'tomyum.png'},
        {no: 0, id: 'FG0007', name: 'Jajangmyeon', category: 'Asia', price: 80000, stock: 14, active: true, image: 'jajangmyeon.png'},
        {no: 0, id: 'FG0008', name: 'Bulgogi', category: 'Asia', price: 88000, stock: 19, active: true, image: 'bulgogi.png'},
        {no: 0, id: 'FG0009', name: 'Kimchi', category: 'Asia', price: 50000, stock: 8, active: false, image: 'kimchi.png'},
        {no: 0, id: 'FG0010', name: 'Fish and Chips', category: 'Western', price: 90000, stock: 24, active: true, image: 'fish-chips.png'},
        {no: 0, id: 'FG0011', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0012', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0013', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0014', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0015', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0016', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0017', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0018', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0019', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0020', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0021', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0022', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0023', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0024', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0025', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0026', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0027', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0001', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0002', name: 'Australian Tender Minutes Steak', category: 'Western', price: 248000, stock: 8, active: true, image: 'aust-tender.png'},
        {no: 0, id: 'FG0003', name: 'Caesar Salad', category: 'Soup & Salad', price: 45000, stock: 16, active: true, image: 'caesar.png'},
        {no: 0, id: 'FG0004', name: 'Creamy Mushroom Soup', category: 'Soup & Salad', price: 55000, stock: 11, active: true, image: 'creamy-mushroom.png'},
        {no: 0, id: 'FG0005', name: 'Chicken Steak', category: 'Western', price: 108000, stock: 17, active: true, image: 'chicken-steak.png'},
        {no: 0, id: 'FG0006', name: 'Tom Yum', category: 'Asia', price: 70000, stock: 18, active: true, image: 'tomyum.png'},
        {no: 0, id: 'FG0007', name: 'Jajangmyeon', category: 'Asia', price: 80000, stock: 14, active: true, image: 'jajangmyeon.png'},
        {no: 0, id: 'FG0008', name: 'Bulgogi', category: 'Asia', price: 88000, stock: 19, active: true, image: 'bulgogi.png'},
        {no: 0, id: 'FG0009', name: 'Kimchi', category: 'Asia', price: 50000, stock: 8, active: false, image: 'kimchi.png'},
        {no: 0, id: 'FG0010', name: 'Fish and Chips', category: 'Western', price: 90000, stock: 24, active: true, image: 'fish-chips.png'},
        {no: 0, id: 'FG0011', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0012', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0013', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0014', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0015', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0016', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0017', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0018', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0019', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0020', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0021', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0022', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0023', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0024', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0025', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0026', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0027', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0001', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0002', name: 'Australian Tender Minutes Steak', category: 'Western', price: 248000, stock: 8, active: true, image: 'aust-tender.png'},
        {no: 0, id: 'FG0003', name: 'Caesar Salad', category: 'Soup & Salad', price: 45000, stock: 16, active: true, image: 'caesar.png'},
        {no: 0, id: 'FG0004', name: 'Creamy Mushroom Soup', category: 'Soup & Salad', price: 55000, stock: 11, active: true, image: 'creamy-mushroom.png'},
        {no: 0, id: 'FG0005', name: 'Chicken Steak', category: 'Western', price: 108000, stock: 17, active: true, image: 'chicken-steak.png'},
        {no: 0, id: 'FG0006', name: 'Tom Yum', category: 'Asia', price: 70000, stock: 18, active: true, image: 'tomyum.png'},
        {no: 0, id: 'FG0007', name: 'Jajangmyeon', category: 'Asia', price: 80000, stock: 14, active: true, image: 'jajangmyeon.png'},
        {no: 0, id: 'FG0008', name: 'Bulgogi', category: 'Asia', price: 88000, stock: 19, active: true, image: 'bulgogi.png'},
        {no: 0, id: 'FG0009', name: 'Kimchi', category: 'Asia', price: 50000, stock: 8, active: false, image: 'kimchi.png'},
        {no: 0, id: 'FG0010', name: 'Fish and Chips', category: 'Western', price: 90000, stock: 24, active: true, image: 'fish-chips.png'},
        {no: 0, id: 'FG0011', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0012', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0013', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0014', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0015', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0016', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0017', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0018', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0019', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0020', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0021', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0022', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0023', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0024', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0025', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0026', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0027', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0001', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0002', name: 'Australian Tender Minutes Steak', category: 'Western', price: 248000, stock: 8, active: true, image: 'aust-tender.png'},
        {no: 0, id: 'FG0003', name: 'Caesar Salad', category: 'Soup & Salad', price: 45000, stock: 16, active: true, image: 'caesar.png'},
        {no: 0, id: 'FG0004', name: 'Creamy Mushroom Soup', category: 'Soup & Salad', price: 55000, stock: 11, active: true, image: 'creamy-mushroom.png'},
        {no: 0, id: 'FG0005', name: 'Chicken Steak', category: 'Western', price: 108000, stock: 17, active: true, image: 'chicken-steak.png'},
        {no: 0, id: 'FG0006', name: 'Tom Yum', category: 'Asia', price: 70000, stock: 18, active: true, image: 'tomyum.png'},
        {no: 0, id: 'FG0007', name: 'Jajangmyeon', category: 'Asia', price: 80000, stock: 14, active: true, image: 'jajangmyeon.png'},
        {no: 0, id: 'FG0008', name: 'Bulgogi', category: 'Asia', price: 88000, stock: 19, active: true, image: 'bulgogi.png'},
        {no: 0, id: 'FG0009', name: 'Kimchi', category: 'Asia', price: 50000, stock: 8, active: false, image: 'kimchi.png'},
        {no: 0, id: 'FG0010', name: 'Fish and Chips', category: 'Western', price: 90000, stock: 24, active: true, image: 'fish-chips.png'},
        {no: 0, id: 'FG0011', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0012', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0013', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0014', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0015', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0016', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0017', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0018', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0019', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0020', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0021', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0022', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0023', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0024', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0025', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0026', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0027', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0001', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0002', name: 'Australian Tender Minutes Steak', category: 'Western', price: 248000, stock: 8, active: true, image: 'aust-tender.png'},
        {no: 0, id: 'FG0003', name: 'Caesar Salad', category: 'Soup & Salad', price: 45000, stock: 16, active: true, image: 'caesar.png'},
        {no: 0, id: 'FG0004', name: 'Creamy Mushroom Soup', category: 'Soup & Salad', price: 55000, stock: 11, active: true, image: 'creamy-mushroom.png'},
        {no: 0, id: 'FG0005', name: 'Chicken Steak', category: 'Western', price: 108000, stock: 17, active: true, image: 'chicken-steak.png'},
        {no: 0, id: 'FG0006', name: 'Tom Yum', category: 'Asia', price: 70000, stock: 18, active: true, image: 'tomyum.png'},
        {no: 0, id: 'FG0007', name: 'Jajangmyeon', category: 'Asia', price: 80000, stock: 14, active: true, image: 'jajangmyeon.png'},
        {no: 0, id: 'FG0008', name: 'Bulgogi', category: 'Asia', price: 88000, stock: 19, active: true, image: 'bulgogi.png'},
        {no: 0, id: 'FG0009', name: 'Kimchi', category: 'Asia', price: 50000, stock: 8, active: false, image: 'kimchi.png'},
        {no: 0, id: 'FG0010', name: 'Fish and Chips', category: 'Western', price: 90000, stock: 24, active: true, image: 'fish-chips.png'},
        {no: 0, id: 'FG0011', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0012', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0013', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0014', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0015', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0016', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0017', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0018', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0019', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0020', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0021', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0022', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0023', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0024', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0025', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0026', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
        {no: 0, id: 'FG0027', name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, stock: 22, active: true, image: 'wagyu-hm.png'},
    ],
    event: [
        {
          no: 1,
          id: 'EV0001', 
          name: 'Family Gathering', 
          date: '2023-12-03', 
          customer: 'PT. Indonesia Raya',
          person: 120,
          status: 'Upcoming',
          phone: '089611113456',
          address: "Jl. KS Tubun 31, Petamburan, Jakarta Pusat",
          food: [
              {id: "FG0001", name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, qty: 120, image: 'wagyu-hm.png'},
              {id: 'FG0003', name: 'Caesar Salad', category: 'Western', price: 45000, qty: 60, image: 'caesar.png'},
              {id: 'FG0004', name: 'Creamy Mushroom Soup', category: 'Soup & Salad', price: 55000, qty: 60, image: 'creamy-mushroom.png'},
          ]
        },
        {
          no: 2,
          id: 'EV0002', 
          name: 'Birthday', 
          date: '2023-12-05', 
          customer: 'John Doe',
          person: 50,
          status: 'Upcoming',
          phone: '089623237890',
          address: "Jl. KS Tubun 72, Petamburan, Jakarta Pusat",
          food: [
            {id: "FG0001", name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, qty: 120, image: 'wagyu-hm.png'},
            {id: 'FG0003', name: 'Caesar Salad', category: 'Western', price: 45000, qty: 60, image: 'caesar.png'},
            {id: 'FG0004', name: 'Creamy Mushroom Soup', category: 'Soup & Salad', price: 55000, qty: 60, image: 'creamy-mushroom.png'}
          ]
        },
        {
          no: 3,
          id: 'EV0003', 
          name: 'Workshop', 
          date: '2023-12-11', 
          customer: 'PT. Indonesia OK',
          person: 80,
          status: 'Upcoming',
          phone: '089622334455',
          address: "Jl. KS Tubun 64, Petamburan, Jakarta Pusat",
          food: [
            {id: "FG0001", name: 'Wagyu Sirloin Steak HM', category: 'Western', price: 350000, qty: 120, image: 'wagyu-hm.png'},
            {id: 'FG0003', name: 'Caesar Salad', category: 'Western', price: 45000, qty: 60, image: 'caesar.png'},
            {id: 'FG0004', name: 'Creamy Mushroom Soup', category: 'Soup & Salad', price: 55000, qty: 60, image: 'creamy-mushroom.png'}
          ]
        },
    ],
    pr: [
       {
          id: 'PR00001', 
          date: '2023-11-24', 
          supplier: 'PT. Sayur Segar', 
          address: 'Jl. Ks Tubun 31, Petamburan, Jakarta Pusat',
          contact: '021 12312 1212',
          company: 'Movenpick',
          department: 'Food & Beverage',
          status: 'Pending',
          step: 1,
          total_items: 10,
          logo: 'company-1.jpg',
          items: [
              {id: 1, kdbrg: 'AX00001', name: 'Fesh Salmon', tipe: 'RM', sbeli: "Kg", qtybeli: 20, kdjenis: 1, no: 1, image: 'fresh-salmon.png'},
              {id: 2, kdbrg: 'AX00002', name: 'Telur Ayam', tipe: 'RM', sbeli: "Peti", qtybeli: 10, kdjenis: 1, no: 2, image: 'telur-ayam.png'},
              {id: 3, kdbrg: 'AX00003', name: 'Bawang Merah', tipe: 'RM', sbeli: "Karung", qtybeli: 5, kdjenis: 1, no: 3, image: 'bawang-merah.png'},
              {id: 4, kdbrg: 'AX00004', name: 'Bawang Putih', tipe: 'RM', sbeli: "Karung", qtybeli: 5, kdjenis: 1, no: 4, image: 'bawang-putih.png'},
              {id: 5, kdbrg: 'AX00005', name: 'Garam', tipe: 'RM', sbeli: "Kg", kdjenis: 2, qtybeli: 20, no: 5, image: 'garam.png'},
              {id: 6, kdbrg: 'AX00006', name: 'Gula', tipe: 'RM', sbeli: "Kg", kdjenis: 2, qtybeli: 20, no: 6, image: 'gula.png'},
              {id: 7, kdbrg: 'AX00007', name: 'Beras Raja', tipe: 'RM', sbeli: "Karung", qtybeli: 6, kdjenis: 2, no: 7, image: 'beras-raja.png'},
              {id: 8, kdbrg: 'AX00008', name: 'Cabe Rawit', tipe: 'RM', sbeli: "Kg", qtybeli: 20, kdjenis: 1, no: 8, image: 'cabe-rawit.png'},
              {id: 9, kdbrg: 'AX00009', name: 'Merica Putih', tipe: 'RM', sbeli: "Kg", qtybeli: 20, kdjenis: 1, no: 9, image: 'merica-putih.png'},
              {id: 10, kdbrg: 'AX00010', name: 'Gula Aren', tipe: 'RM', sbeli: "Kg", qtybeli: 20, kdjenis: 1, no: 10, image: 'gula-aren.png'},
            ] 
        },
        {
          id: 'PR00002', 
          date: '2023-11-23', 
          supplier: 'PT. Fresh Market', 
          address: 'Jl. Ks Tubun 72, Petamburan, Jakarta Pusat',
          contact: '021 12312 1212',
          company: 'Movenpick',
          department: 'Food & Beverage',
          status: 'Approved PR',
          step: 2,
          total_items: 15,
          logo: 'company-2.jpg',
          items: [
              
            ] 
        },
        {
          id: 'PR00003', 
          date: '2023-11-24', 
          supplier: 'PT. Sembako Subur', 
          address: 'Jl. Ks Tubun 64, Petamburan, Jakarta Pusat',
          contact: '021 12312 1212',
          company: 'Movenpick',
          department: 'Food & Beverage',
          status: 'Rejected',
          step: 0,
          total_items: 17,
          logo: 'company-3.jpg',
          items: [
              
            ] 
        },
        {
          id: 'PR00004', 
          date: '2023-11-23', 
          supplier: 'PT. Makin Kesana Makin Kesini', 
          address: 'Jl. Ks Tubun 89, Petamburan, Jakarta Pusat',
          contact: '021 12312 1212',
          company: 'Movenpick',
          department: 'Food & Beverage',
          status: 'Approved PO',
          step: 3,
          total_items: 15,
          logo: 'company-4.jpg',
          items: [
              {id: 1, kdbrg: 'AX00001', name: 'Fesh Salmon', tipe: 'RM', sbeli: "Kg", qtybeli: 20, kdjenis: 1, no: 1, image: 'fresh-salmon.png'},
              {id: 2, kdbrg: 'AX00002', name: 'Telur Ayam', tipe: 'RM', sbeli: "Peti", qtybeli: 10, kdjenis: 1, no: 2, image: 'telur-ayam.png'},
              {id: 3, kdbrg: 'AX00003', name: 'Bawang Merah', tipe: 'RM', sbeli: "Karung", qtybeli: 5, kdjenis: 1, no: 3, image: 'bawang-merah.png'},
              {id: 4, kdbrg: 'AX00004', name: 'Bawang Putih', tipe: 'RM', sbeli: "Karung", qtybeli: 5, kdjenis: 1, no: 4, image: 'bawang-putih.png'},
              {id: 5, kdbrg: 'AX00005', name: 'Garam', tipe: 'RM', sbeli: "Kg", kdjenis: 2, qtybeli: 20, no: 5, image: 'garam.png'},
              {id: 6, kdbrg: 'AX00006', name: 'Gula', tipe: 'RM', sbeli: "Kg", kdjenis: 2, qtybeli: 20, no: 6, image: 'gula.png'},
              {id: 7, kdbrg: 'AX00007', name: 'Beras Raja', tipe: 'RM', sbeli: "Karung", qtybeli: 6, kdjenis: 2, no: 7, image: 'beras-raja.png'},
              {id: 8, kdbrg: 'AX00008', name: 'Cabe Rawit', tipe: 'RM', sbeli: "Kg", qtybeli: 20, kdjenis: 1, no: 8, image: 'cabe-rawit.png'},
              {id: 9, kdbrg: 'AX00009', name: 'Merica Putih', tipe: 'RM', sbeli: "Kg", qtybeli: 20, kdjenis: 1, no: 9, image: 'merica-putih.png'},
              {id: 10, kdbrg: 'AX00010', name: 'Gula Aren', tipe: 'RM', sbeli: "Kg", qtybeli: 20, kdjenis: 1, no: 10, image: 'gula-aren.png'},
              {id: 11, kdbrg: 'AX00011', name: 'Kecap Bango', tipe: 'RM', sbeli: "Box", qtybeli: 10, kdjenis: 2, no: 11, active: true, image: 'kecap-bango.png'},
              {id: 12, kdbrg: 'AX00012', name: 'Kecap ABC', tipe: 'RM', sbeli: "Box", qtybeli: 10, kdjenis: 2, no: 12, active: true, image: 'kecap-abc.png'},
              {id: 13, kdbrg: 'AX00013', name: 'Sauce Tomat Belibis', tipe: 'RM', sbeli: "Box", qtybeli: 10, kdjenis: 2, no: 13, active: true, image: 'tomat-belibis.png'},
              {id: 14, kdbrg: 'AX00014', name: 'Saori Saus Tiram', tipe: 'RM', sbeli: "Box", qtybeli: 10, kdjenis: 2, no: 14, active: true, image: 'saori-saus-tiram.png'},
              {id: 15, kdbrg: 'AX00015', name: 'Kaldu Jamur', tipe: 'RM', sbeli: "Box", qtybeli: 10, kdjenis: 2, no: 15, active: true, image: 'kaldu-jamur.png'},
            ] 
        },
    ]
  },
  getters: {
  },
  mutations: {
  },
  actions: {
  },
  modules: {
    auth
  },

  plugins: [createPersistedState({
    paths: ['auth']
  })]
})
